- name: Docker service is started
  service:
    name=docker
    state=started

- name: Swarm manage is running
  docker:
    name: swarm-manage
    image: swarm
    expose: 4000
    ports: 4000:4000
    docker_api_version: 1.18
    command: manage -H tcp://0.0.0.0:4000 --addr={{ip}}:4000 --replication consul://{{ ip }}:8500/docker_swarm